### ISSUE TITLE
Built in modules like 'os' do not work with EASE jython integration

### ISSUE THREAD

**Issue by tracymiranda** [eclipse-ease-addons/jython#1]
To reproduce, paste the following into a jython script and run as an EASE application

import os 
os.listdir("c:\\Results\\")

(Replace with appropriate path for your os)

Instead of running, this gives the following error

I get this error:
Traceback (most recent call last):
  File "(none)", line 2, in <module>
TypeError: 'javapackage' object is not callable

**Comment by Pontesegger** [comment]
somewhen we replaced the extracted version of the jython lib with the jar version. I've updated the update site. Please fetch the new version.
